services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - product-service
  product-service:
    build: ./services/product
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - SERVICE_NAME=product
      - MONGO_URI=mongodb+srv://softypy:softypy123@cluster0.8a2ra.mongodb.net/product?retryWrites=true&w=majority&appName=Cluster0
