version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./services/user
    ports:
      - "4002:4002"
    env_file:
      - ./services/user/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  product-service:
    build: ./services/product
    ports:
      - "4001:4001"
    env_file:
      - ./services/product/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-service:
        condition: service_started

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
